version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/model:/app/model  # Monte le modèle pour qu'il soit accessible dans le conteneur
    restart: always  # Redémarrage automatique du backend
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Monte tout le code du frontend
    restart: always  # Redémarrage automatique du frontend
    networks:
      - mynetwork

networks:
  mynetwork:
